name: Trigger SNS for dynamic pipeline maker lambda

on: [create, delete]
  #create:
  #  branches:
  #    - feature/test-sns-pipeline-shared-account
  #delete:
  #  branches:
  #    - feature/test-sns-pipeline-shared-account

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ACCESS_AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
          role-to-assume: arn:aws:iam::833843385348:role/account-deployer
          role-duration-seconds: 3600
      #- name: Push pipieline.template.yaml to s3 repo-name branch 
      # aws --profile shared-poweruser s3 cp project.template.yaml s3://au-slyp-com-shared-cross-account-template-base-poc/shared-deployments/sample-project/master/project.template.yaml --acl private
      # aws --profile shared-poweruser s3 cp pipeline.template.yaml s3://au-slyp-com-shared-cross-account-template-base-poc/shared-deployments/sample-project/feature/test-release-branch/pipeline.template.yaml --acl private
      - name: AWS SNS - Publish Topic w/ SessionToken
        uses: smurphnturf/publish-sns-topic@1.1-beta
        with:
          MESSAGE: '{"repository":"${{ github.repository }}","ref":"${{ github.ref }}","base_ref":"${{ github.base_ref }}","event_name":"${{ github.event_name }}"}'
          TOPIC_ARN: "arn:aws:sns:ap-southeast-2:833843385348:Serverless-CICD-cross-account-poc-LambdaStack-SPBPKF5KH6KK-PipelineSNSTopic-JUQ2482VTBUZ"